---
- name: "update apt package"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade package"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies"
  become: yes
  apt:
    autoremove: yes

- name: "install dep"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: directory
  file:
    path: ~/web
    state: directory
  
- name: index page
  template:
    src: files/index.js
    dest: ~/web/index.js

- name: Execute "nodejs"
  shell: |
    pm2 start ~/web/index.js -f